# I wrote this with ChatGPT
# Vibe DevOpsing
name: Build Native

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - if: runner.os == 'Windows'
        run: git config --global core.autocrlf true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Cache Cargo registry and build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo Make
        run: cargo install cargo-make

      - name: Run Cargo Make export task
        run: cargo make export

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: package.*
