# I wrote this with ChatGPT
# Vibe DevOpsing
name: Build and Export

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry and build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo Make
        run: cargo install cargo-make

      - name: Run Cargo Make export task
        run: cargo make export

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.*
